### ISSUE TITLE
Error when uploading from ShareX

### ISSUE THREAD

**Issue by camjac251** [milasoftwaregroup/imago#5]
Opening in reference to #4 
I'm running this directly on a public IP (no nginx) and  get an error when I try to upload with ShareX

```bash
[2020-04-22 20:07:31,575] ERROR in app: Exception on /api/upload [POST]
Traceback (most recent call last):
  File "/root/anaconda3/envs/imago/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/anaconda3/envs/imago/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/anaconda3/envs/imago/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/anaconda3/envs/imago/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/root/anaconda3/envs/imago/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/anaconda3/envs/imago/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/imago/imagoweb/plugins/api.py", line 219, in upload_file
    file.save(f"static/uploads/{discriminator}")
  File "/root/anaconda3/envs/imago/lib/python3.6/site-packages/werkzeug/datastructures.py", line 3066, in save
    dst = open(dst, "wb")
FileNotFoundError: [Errno 2] No such file or directory: 'static/uploads/aM8OBnt2.png'
[2020-04-22 20:07:32,618] ERROR in app: Exception on /api/upload [POST]
Traceback (most recent call last):
  File "/root/anaconda3/envs/imago/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/anaconda3/envs/imago/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/anaconda3/envs/imago/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/anaconda3/envs/imago/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/root/anaconda3/envs/imago/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/anaconda3/envs/imago/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/imago/imagoweb/plugins/api.py", line 219, in upload_file
    file.save(f"static/uploads/{discriminator}")
  File "/root/anaconda3/envs/imago/lib/python3.6/site-packages/werkzeug/datastructures.py", line 3066, in save
    dst = open(dst, "wb")
FileNotFoundError: [Errno 2] No such file or directory: 'static/uploads/Oh6vhksQ.png
```
I'm running this in a conda environment as opposed to a virtual environment.

**Comment by Jack-Gledhill** [comment]
The server is intended to be used with Nginx on a virtual environment or no venv at all. Unfortunately I'm not familiar with Anaconda and the software you're using to publicise the site. 

If someone could submit a Pull Request that could fix this I'd appreciate it.

**Comment by camjac251** [comment]
It's happening without conda too. Tried running it without having it installed. Installed the requirements globally this time with the systems python version 3.7

I get the same error unfortunately but ShareX also outputs something
```
Error message:
The remote server returned an error: (500) Internal Server Error.

Request URL:
http://IP:5000/api/upload

Status code:
(500) INTERNAL SERVER ERROR

Headers:
Content-Length: 3504
Content-Type: text/html; charset=utf-8
Date: Wed, 22 Apr 2020 20:46:56 GMT

Response text:
<!-- 
Copyright (C) Mila Software Group 2018-2020
------------------------------------------- 
-->

<!DOCTYPE html>
<html>
<head>
    <meta id="version-proxy" data-version-info='{"hash": "3.6.3-stable", "major": 3, "minor": 6, "number": "v3.6.3", "patch": 3, "release": "stable"}'>
    <meta property="og:title" content="A ShareX file server">
                   <meta name="twitter:title" content="A ShareX file server">

                   <meta name="theme-color" content="#4196f7">
                   
                   <link rel="canonical" href="https://imagocdn.com">
                   <meta property="og:url" content="https://imagocdn.com">
                   <meta name="twitter:url" content="https://imagocdn.com">
                   
                   <meta name="description" content="Imago is an efficient, highly-configurable ShareX upload server complete with its own dashboard and Administrator panel. With it, you can upload any file you like, be it an image, video, audio file or just plain text!">
                   <meta property="og:description" content="Imago is an efficient, highly-configurable ShareX upload server complete with its own dashboard and Administrator panel. With it, you can upload any file you like, be it an image, video, audio file or just plain text!">
                   <meta name="twitter:description" content="Imago is an efficient, highly-configurable ShareX upload server complete with its own dashboard and Administrator panel. With it, you can upload any file you like, be it an image, video, audio file or just plain text!">
                   
                   <meta property="og:image" content="meta/image.jpg">
                   <meta name="twitter:image" content="meta/image.jpg">
                   <meta property="og:thumbnail" content="meta/thumbnail.jpg">
                   
                   <meta property="og:site_name" content="Imago CDN">
                   <meta property="og:type" content="website">

    
    <!-- Stylesheet imports -->
    <link rel="stylesheet" href="/static/styles/index.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

    <!-- Metadata tags -->
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="shortcut icon" href="/static/assets/favicon.ico">

    
    

    
        <title>Imago</title>
    
</head>
<body>
    
    

    
  <!-- JavaScript library imports -->
  <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
  <script src="/static/scripts/index.js"></script>
  <script src="/static/scripts/devtools-detect.js"></script>
  <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.4/clipboard.min.js"></script>




    
    
</body>
</html>


    <link rel="stylesheet" href="/static/styles/errors.css">



    <title>500 - Internal server error</title>



    <div class="content">
        <h1 class="emoticon">(╯°□°)╯</h1>
        <br>
        <p class="code">500 - It&#39;s not you, it&#39;s us</p>
        <h1>Mmm, toasted server.</h1>
        <h3>Uh oh... Fire in the server room!</h3>
        <p class="return" onclick="window.history.back();"><a class="arrow">←</a>&nbsp; Go back</p>
    </div>


Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)
```

**Comment by Jack-Gledhill** [comment]
I have a funny feeling that the error is being raised because the /static/uploads folder doesn't exist. In the project directory, create a folder named "uploads" in the static folder. If that doesn't work or that directory already exists, let me know.

**Comment by camjac251** [comment]
That worked. Everything is working now. Thank you. I seem to be stuck at 16MB/s on upload speeds.

**Comment by Jack-Gledhill** [comment]
Your poor upload speeds could be a limitation of Flask or Gevent which is used to serve the site. I really don't know what could be done about that. Do you mean 16 Mega _bytes_ (M**B**) or 16 Mega _bits_ (M**b**)?

**Comment by camjac251** [comment]
16 Megabytes. I'm trying to find a replacement to a PHP file/image host that is able to max my gigabit line. Although large files with PHP take a while to process on servers.

**Comment by Jack-Gledhill** [comment]
Generally speaking this server isn't intended to be used as a file server for uploading large files. It's certainly capable of it but it won't do it well.

Given that PHP works closer to machine code than Python does, it's highly likely that you won't match the speed of your PHP server even if this was written in Node.js

**Comment by camjac251** [comment]
Would there be advantages to not using PHP though? With this other PHP file host I've been testing, PHP/nginx end up copying the file from temp before it can process after an upload. Is it different with python?

**Comment by Jack-Gledhill** [comment]
Python is very powerful and it's hard to say whether or not you'd be able to fully replicate this site in PHP. That being said, Flask does seem to receive the file data directly from the client rather than saving it temporarily before processing it.
